### ISSUE TITLE
Windows has no HOME environment variable

### ISSUE THREAD

**Issue by danieldaeschle** [Jaffa/amazon-music#10]
i would suggest to use a local file indead of home as fallback.

https://github.com/Jaffa/amazon-music/blob/ca0f6d6796e2fd7a17f271bcc6c13dee2aaf9155/amazonmusic.py#L68

would look like this:

```Python
local = os.path.dirname(os.path.realpath(__file__))
cookie_path = cookies or '{}/.amazonmusic-cookies.dat'.format(os.environ.get('HOME',  local))
```

**Comment by Jaffa** [comment]
That's a sensible ultimate fallback, but on non-Cygwin/non-WSL Windows, an intermediate would be `LOCALAPPDATA`, that seems to default to (on my machine):

    LOCALAPPDATA=C:\Users\andrew\AppData\Local

**Comment by danieldaeschle** [comment]
Yes, but the code at the moment causes a crash which should be fixed.

**Comment by Jaffa** [comment]
Yep.
