### ISSUE TITLE
Great repo

### ISSUE THREAD

**Issue by danieldaeschle** [Jaffa/amazon-music#2]
Please provide more attributes etc :)

Then we can create our own android app or linux desktop app which works better x)

**Comment by Jaffa** [comment]
Thanks for your comment!

Are there any particular attributes/behaviours you'd like prioritised?

**Comment by danieldaeschle** [comment]
Hey! Thanks for your reply. I want to create my own music client for linux.

A very important function is to list all songs.

I would try to create PRs to make this repo more pythonic like if you want.

There are also some bugs which i can fix.

**Comment by Jaffa** [comment]
That'd be much appreciated, thank you!

**Comment by danieldaeschle** [comment]
Did you saw my PR?

**Comment by Jaffa** [comment]
I did, thanks. I'm hoping to get to them this weekend.
