### ISSUE TITLE
Support downloading tracks I've bought?

### ISSUE THREAD

**Issue by rossburton** [Jaffa/amazon-music#24]
I'm trying to find a way to basically have a cron that downloads all of the music that I've bought on Amazon to my NAS.  Can this expose API to give a URL to download files that I've purchased?

**Comment by Jaffa** [comment]
No, I'm afraid not.

Currently there is an issue getting high-quality playback data, which has stalled the development, as Amazon have moved to encrypted data played back in the browser.

I haven't investigated how Amazon present purchased tracks through the web player, but suspect it won't be easy.
