### ISSUE TITLE
Drop python2 support

### ISSUE THREAD

**Issue by danieldaeschle** [Jaffa/amazon-music#7]
Just because python2 isn't relevant anymore...

**Comment by Jaffa** [comment]
It's not _supposed_ to be relevant, but it's not a massive overhead to support _at the moment_ (although the new new style `.format` strings are probably not supported on Python 2?) and I still come across environments and distributions that default to Python 2, treating Python 3 as a second class citizen :-(

**Comment by danieldaeschle** [comment]
Okay, still on python2 as default? Haha
Python 3 is etablished very often now. Most of the big libraries has started to drop Python 2 support.

format example:

```Python
# Python 2
"%s" % my_str

# Python 2 & 3
"{0}".format(my_str)  # or
"{my_str}".format(my_str="my_str")

# Python 3.6 only
my_str = "my_str"
f"{my_str}"
```
I would recommend to use `.format()`

**Comment by Jaffa** [comment]
Marked as `wontfix`, but - at some point - we will.
