### ISSUE TITLE
backslash causes No connection adapters

### ISSUE THREAD

**Issue by markfoodyburton** [Jaffa/amazon-music#8]
On this line,  I get a No Connected adapters...
https://github.com/Jaffa/amazon-music/blob/ca0f6d6796e2fd7a17f271bcc6c13dee2aaf9155/amazonmusic.py#L179

Removing the prepended '/' makes it "work", but then the URL is a 404
The url generated seems to be: https://music.amazon.fr/api/EU

Any ideas?

**Comment by danieldaeschle** [comment]
I will take a look on it soon :)

**Comment by danieldaeschle** [comment]
I don't live in france, does music.amazon.fr exists? I only know .com

**Comment by markfoodyburton** [comment]
Hi, thanks for looking, yes .fr exists. Actually, I didn't change your code, so clearly it automatically redirects you to the 'right' country site... 
So, for instance, I am able to search using
**https://music.amazon.fr/search/needle**

**Comment by danieldaeschle** [comment]
Can you send me your code? I want to try it in my country if i also get a 404.

**Comment by danieldaeschle** [comment]
According to the code before my PR it should be: `'{}/{}/api/{}'.format(self.url, self.region, endpoint)` then it works :)
